language: node_js
node_js:
- '10'
os:
  - linux
  - osx
branches:
  only:
    - master
    - dev
before_script:
  - npm install git+https://gitlab+deploy-token-3:${DEPLOY_GITLAB_TOKEN}@gitlab.insysbio.com/metelkin/qs3p-js.git
script:
  - qs3p build
after_success:
  - echo "Sending the files to dist branch..."
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git clone -b dist --single-branch https://github.com/insysbio/heta-case-mini tmp
  - cd tmp
  - cp -rf ../dist/* ./
  - cp -rf ../static/* ./
  - git add --all
  - git commit --allow-empty -m "Travis build $TRAVIS_BUILD_NUMBER"
  - git push https://${GH_TOKEN}@github.com/insysbio/heta-case-mini HEAD:dist
