language: r
r_packages:
  - lattice
#  - mrgsolve # cannot be installed in this way
#node_js: # this part works only when language: node_js
#  - '10'
cache:
  npm: true
  R: true
os:
  - linux
#  - osx # problems with npm install -g git+https://... in node 6
branches:
  only:
    - master
    - dev
before_install:
  - npm -v
  - node -v
  - Rscript --version
install:
  - npm install -g git+https://${GL_TOKEN}@gitlab.insysbio.com/metelkin/qs3p-js.git
script:
  - qs3p build
  - R -e "install.packages('mrgsolve');"
#  - R -e "source('./R/run-mrgsolve.R');" # alternative solution
#  - /home/travis/R-bin/bin/Rscript ./R/run-mrgsolve.R
  - Rscript -e ./R/run-mrgsolve.R
after_success:
  - echo "Sending the files to gh-pages branch..."
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git clone -b gh-pages --single-branch https://github.com/insysbio/heta-case-mini tmp
  - cd tmp
  - cp -rf ../dist/* ./
  - cp -rf ../static/* ./
  - git add --all
  - git commit --allow-empty -m "Travis build $TRAVIS_BUILD_NUMBER"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git push https://${GH_TOKEN}@github.com/insysbio/heta-case-mini HEAD:gh-pages; fi
