%%%% This code was generated by qs3p-js of v0.4.22
% 

function y = matlab_Init(p)

y = zeros(3, 1);

%%% Initialization of dynamic records
y(1) = 1; % comp1,  ()
y(2) = (10) * y(1); % A,  ()
y(3) = (0) * y(1); % B,  ()

end
