%%%% This code was generated by qs3p-js of v0.4.22
% 

function [ode_func, out_func] = matlab_Model()
    ode_func = @Model;
    out_func = @OutputFunc;

    % shared variable
    shared_values = zeros(1, 4);

    function status = OutputFunc(t, y, flag)
        persistent integrator;

        switch (flag)
        case 'init'
        integrator = shared_values;
        case []
        integrator = [integrator; shared_values];
        case 'done'
        assignin('base', 'output', integrator);
        end
        status = 0;
    end

    function dydt = Model(t, y, p)

        dydt = zeros(3, 1);

        %%% Dynamic records annotation
        %1 - comp1,  () 
        %2 - A,  () 
        %3 - B,  () 

        %%% Output records
        %  () 
        comp1 = y(1);
        %  () 
        B = y(3) / comp1;
        %  () 
        A = y(2) / comp1;
        %  () 
        r1 = p(1) * A * comp1;
        shared_values = [comp1, B, A, r1];

        %%% Differential equations
        dydt(1) = 0;
        dydt(2) = -r1;
        dydt(3) = 2*r1;
    end

end