# This workflow build Heta platform and share results in "dist" branch

name: Build and Share

defaults:
  run:
    shell: bash
    
on:
  push:
    branches: [ master, '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Install and build
      run: |
        npm i -g heta-compiler@latest
        heta build
    - name: Copy other files to dist
      run: |
        cp -f ./static/index.md ./dist/
        tar -zcf ./dist/matlab.tar.gz -C ./dist/matlab .
        tar -zcf ./dist/simbio.tar.gz -C ./dist/simbio .
        mkdir -p ./dist/plots
#        cp -rf ./diagnostics/dbsolve/*.png ./dist/plots/
#        cp -rf ./diagnostics/simbio/*.png ./dist/plots/
#        cp -rf ./diagnostics/matlab/*.png ./dist/plots/
    - name: Deploy to "dist" branch only for "master" and "share" pushes
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/share' ) }}
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
        CLEAN: false
