# This workflow build Heta platform and share results in "dist" branch

name: Build and Share

defaults:
  run:
    shell: bash
    
on:
  push:
    branches: [ master, share ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install and build
      run: |
        npm i -g heta-compiler@latest
        heta build
    - name: Set up R 3.6
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6'
    - name: Run R code
      run: |
        Rscript -e 'install.packages(c("lattice", "mrgsolve"));'
        Rscript ./R/run-mrgsolve.R
    - name: Julia install
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.6'
        arch: x86
    - name: HetaSimulator install
      run: |
        julia -e 'using Pkg; Pkg.add(path="https://github.com/hetalang/HetaSimulator.jl"); Pkg.add("Plots")'
        pwd
        julia ./julia/run.jl
    - name: Copy other files to dist
      run: |
        cp -f ./static/index.md ./dist/
        cp ./julia-plot-1.png ./dist/
        cp ./julia-plot-2.png ./dist/
        tar -zcf ./dist/matlab.tar.gz -C ./dist/matlab .
        tar -zcf ./dist/simbio.tar.gz -C ./dist/simbio .
        tar -zcf ./dist/julia.tar.gz -C ./dist/julia .
        # mkdir -p ./dist/plots
    - name: Deploy to "dist" branch only for "master" and "share" pushes
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/share' ) }}
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
        CLEAN: true
