# This workflow build Heta platform and share results in "dist" branch

name: Build and Share

defaults:
  run:
    shell: bash
    
on:
  push:
    branches: [ master, share ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: insysbio/qsp-platforms-builder:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install and build
      run: |
        npm i -g heta-compiler@0.8.4
        heta build
    - name: Run R code
      run: |
        Rscript ./R/run-mrgsolve.R
    - name: HetaSimulator run
      run: |
        pwd
        julia --sysimage=/opt/julia/sysimages/hetasimulator.so ./julia/run.jl
    - name: Copy other files to dist
      run: |
        cp -f ./static/index.md ./dist/
        cp ./julia-plot-1.png ./dist/
        cp ./julia-plot-2.png ./dist/
        tar -zcf ./dist/matlab.tar.gz -C ./dist/matlab .
        tar -zcf ./dist/simbio.tar.gz -C ./dist/simbio .
        tar -zcf ./dist/julia.tar.gz -C ./dist/julia .
        # mkdir -p ./dist/plots
    - name: Deploy to "dist" branch only for "master" and "share" pushes
      if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/share' ) }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
        clean: true
